
server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
      overrideNone: true
        #git:
          #uri: https://github.com/wumingrong/springcloud/ #配置git仓库地址
          #searchPaths: globalConfig #配置仓库路径
          #username: #访问git仓库的用户名
          #password: #访问git仓库的用户密码
      #label: master #配置仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/