eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enabled: true

api:
  name: test
  url: https://tcc.taobao.com
  value: /cc/json/mobile_tel_segment.htm
